Update airdrop.yml

diff --git a/.github/workflows/airdrop.yml b/.github/workflows/airdrop.yml
--- a/.github/workflows/airdrop.yml
+++ b/.github/workflows/airdrop.yml
@@ -35,6 +35,11 @@ jobs:
           wget https://github.com/cosmos/mainnet/raw/master/genesis.cosmoshub-4.json.gz
           gzip -d genesis.cosmoshub-4.json.gz
           mv genesis.cosmoshub-4.json genesis.json
+          if [ $(echo '{"test":true}' | jq empty > /dev/null 2>&1; echo $?) -eq 0 ]; then
+          echo "JSON is valid"
+          else
+          echo "JSON is invalid"
+          fi
           ./junod export-airdrop-snapshot juno genesis.json exchanges.json snapshot.json --juno-whalecap=50000000000
 
  # junod export-airdrop-snapshot [airdrop-to-denom] [input-genesis-file] [input-exchange-addresses] [output-snapshot-json] --juno-whalecap=[juno-whalecap] [flags]
